# Generated by Django 5.1.7 on 2025-04-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageProcessingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sift_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="processed/sift/"
                    ),
                ),
                (
                    "ransac_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="processed/ransac/"
                    ),
                ),
                (
                    "harris_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="processed/harris/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
