# Generated by Django 5.1.7 on 2025-04-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_processing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageprocessingresult",
            name="name",
            field=models.CharField(default="unnamed", max_length=100),
        ),
    ]
