# Generated by Django 5.1.7 on 2025-04-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_processing", "0002_imageprocessingresult_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imageprocessingresult",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="imageprocessingresult",
            name="harris_image",
            field=models.ImageField(null=True, upload_to="processed/"),
        ),
        migrations.AlterField(
            model_name="imageprocessingresult",
            name="ransac_image",
            field=models.ImageField(blank=True, null=True, upload_to="processed/"),
        ),
        migrations.AlterField(
            model_name="imageprocessingresult",
            name="sift_image",
            field=models.ImageField(null=True, upload_to="processed/"),
        ),
    ]
